### ISSUE TITLE
Auto Respring Respring Loop

### ISSUE THREAD

**Issue by kurtbain250** [pwn20wndstuff/Undecimus#1343]
**Describe the bug**
Toggling Auto-Respring ON under settings causes endless respring loop

**To Reproduce**
1. Reboot
2. Open Unc0ver vr 3.5.x and above and toggle auto respring on
3. Jailbreak
4. Endless respring

**Screenshots**
I can post a video if requested

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPhone 6S
 - unc0ver Version: 3.5.5 

 - iOS Version: 12.4
 - iOS Device: iPhone 7 Plus
 - unc0ver Version: 3.5.5 

 - iOS Version: 12.4
 - iOS Device: iPhone X
 - unc0ver Version: 3.5.5 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Notes**
At first I suspected a tweak causing was the issue but after some extensive testing i actually believe this bug is happening thanks to unc0vers amazing speed lol, the device reboots too soon, im going to try adding a small wait before the auto respring and see if that works. If it does and this issue is still present in the latest build ill submit a pull request.

**Thanks**
I just wanted to take a second to thank the unc0ver team and jailbreak community. Its been a wild ride.

**Comment by kurtbain250** [comment]
Just noticed latest s/c isnt up. All good but i cant test a fix so next beta please add a small wait (maybe a second) before respiring using the auto respring toggle and see if that fixes the respring loop issue.

**Comment by soum91** [comment]
Do you have any of Flex or Safari Plus? If you have, removing will solve unless there is any other tweak causing it. Alternatively you can jailbreak with RSD turned off. This was solved by Pwn in pre-12.4 version. Something has broken once again for sure. Sure Pwn fix it when he notices and have free time.

**Comment by kurtbain250** [comment]
Auto respring issue is still present in the latest 3.70b3, now it kind of works but the app crashes to the homescreen where we see a long pause then finally a respring. Sometimes it also freezes on deinitialize jailbreak. FYI to soum91 please read the original post. Tested on two of my test devices with no tweaks and a fresh rootfs restore. And again this was tested on a fresh rootfs restore with the issue persisting. Funny, auto respring works as expected if you "re-jailbreaking" once already jailbroken but still displays that annoying "credits" prompt before actually resprining. Anyways, lost hope is this bug ever being addressed but at least i tried. Chimera works no problem, also doesnt shove credits in your face as much as it can.
