### ISSUE TITLE
“Unable to repair system”

### ISSUE THREAD

**Issue by ENDERZOMBI102** [pwn20wndstuff/Undecimus#1629]

**Comment by ENDERZOMBI102** [comment]
When jb, the process is normal until 21/31, here the error “unable to repair system” pop up, and then the app crashes, i’m using sock puppet 3.0

To Reproduce Steps to reproduce the behavior:

Click on jailbreak
Wait for 21/31
See error

(![Image](https://i.imgur.com/mzAfNyz.jpg))

Device (please complete the following information):

iOS Version: 12.1.3
iOS Device: IPhone SE
unc0ver Version: 3.7.0 b3
Place an "x" between the brackets if true:

[ ] this is a bug others will be able to reproduce
[x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
[x] this issue is present after a rootfs restore
[x] this issue is present on the latest version of unc0ver
Logs If applicable, add logs or error messages here.

**Comment by mtulepkaliev** [comment]
Had the same issue after updating essential in Cydia, managed to get back  into a jailbroken  state by re-opening unc0ver and respringing from "Restart Springboard" in the settings however trying to install/ upgrade anything will return an error, probably due to something updated in the cydia essential upgrades

**Comment by alexmaten** [comment]
try to restoreFS and retry, this worked for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rigolas** [comment]
> Had the same issue after updating essential in Cydia, managed to get back into a jailbroken state by re-opening unc0ver and respringing from "Restart Springboard" in the settings however trying to install/ upgrade anything will return an error, probably due to something updated in the cydia essential upgrades

Did you get "Sub-process /usr/libexec/cydia/cydo returned an error code (2)?" I'm currently stuck  in this loop and can't seem to install anything with Cydia. I can't seem to get back into a jailbroken state.

**Comment by alexmaten** [comment]
>> Had the same issue after updating essential in Cydia, managed to get back into a jailbroken state by re-opening unc0ver and respringing from "Restart Springboard" in the settings however trying to install/ upgrade anything will return an error, probably due to something updated in the cydia essential upgrades ...

@Rigolas 

Solution: https://github.com/pwn20wndstuff/Undecimus/issues/1626#issuecomment-560078610

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rend0e** [comment]
I think the problem is that new essential cydia updates are causing cydia to have trouble updating/installing ‘Launch Daemon Controller’ (launchctl) which is showing on cydia as cydo error code 2.

If you check the log on the unc0ver app it says:
dpkg: warning: 'launchctl' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable 
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin 
E: Sub-process /usr/bin/dpkg returned an error code (2)

Which means that ‘Launch Daemon Controller’ (launchctl) is missing and causing problems. To fix it you have to forcibly install Launch Daemon Controller’ (launchctl) via terminal or ssh with dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Instructions: 
Download https://apt.bingner.com/debs/1443.00/launchctl_22-1_iphoneos-arm.deb to filza
Open terminal (or ssh) and enter:
su
cd var/mobile/Documents
dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Restoring rootfs may not fix the problem because cydia essential updates will require you to install the problematic ‘Launch Daemon Controller’ (Launchctl) which would cause the whole problem again. So you must forcibly install Launch Daemon Controller to completely fix the problem.

**Comment by Rend0e** [comment]
I believe the problem is now fixed https://mobile.twitter.com/sbingner/status/1201381940646924290?s=21

**Comment by Emiougus** [comment]
It's not, I'm having the same issue with attempting to update the new packages, even after rootFS this problem still persists(as of like 3 hours ago when I tried to fix this by restoring rootFS then updating all packages from cydia). I'm on and Iphone 6 plus 12.1.1

**Comment by ENDERZOMBI102** [comment]
The subject is going a little off topic :(
The error here not complain cydia
