### ISSUE TITLE
Launch Daemon Controller’ (launchctl) update is causing ‘Sub-process /usr/libexec/cydia/cydo returned an error code (2)’ and ‘Unable to repair system’

### ISSUE THREAD

**Issue by Rend0e** [pwn20wndstuff/Undecimus#1631]
The Launch Daemon Controller’ (launchctl) update is causing ‘Sub-process /usr/libexec/cydia/cydo returned an error code (2)’ in cydia when installing/uninstalling tweaks.

Unc0ver app shows the message ‘Unable to repair system’ when jailbreaking with the log mentioning:
dpkg: warning: 'launchctl' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable 
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin 
E: Sub-process /usr/bin/dpkg returned an error code (2)

The problem persists after restoring rootFS and updating essential packages because cydia requires you to install essential packages including the bugged ‘Launch Daemon Controller’ (launchctl) update.

The workaround to this problem is to forcibly install Launch Daemon Controller’ (launchctl) via terminal or ssh with dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Instructions to workaround:
Download https://apt.bingner.com/debs/1443.00/launchctl_22-1_iphoneos-arm.deb to filza
Open terminal (or ssh) and enter:
su
cd var/mobile/Documents
dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

**To Reproduce**
1. Update essential tweaks
2. Error occurs

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iPad Air 2
 - unc0ver Version: 3.7.0~b3

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Rend0e** [comment]
I assume this have been fixed https://mobile.twitter.com/sbingner/status/1201381940646924290

**Comment by abigchopstick** [comment]
no it's not fixed, it's happening again.

iOS 12.4 iPhone XR

**Comment by fizzy-joon** [comment]
Hi
I got this issue and it's been about 3 weeks and am trying every single TuT i can find on internet, but yet no luck.
I hope someone gets some free time and reply please.

My Device info:
iPad5,1 (iPad mini4) iOS 11.4 - Cydia64_1.1.32~b22

**Comment by viki512** [comment]
![22C6EFED-5002-4AC4-8D52-82E877EC8C3A](https://user-images.githubusercontent.com/61298470/74990901-d8cc5300-5444-11ea-9343-9d2c5c66b696.jpeg)


![E49F0375-3D3F-437F-A565-B096365F43A6](https://user-images.githubusercontent.com/61298470/74990910-dd910700-5444-11ea-997d-888f60599241.png)

For cydo error (100) and (1) do same setting With Filza or ifile and will work. It’s works for me very well sorry for bad English

**Comment by fizzy-joon** [comment]
Thanks for reply @viki512, I did unjailbreak with unc0ver and re-jailbreak again and I had my .dep files on (Filza) and installed it all back.
I wish your reply was a bit early, but thank you so much.

**Comment by viki512** [comment]
is that yesterday I had that problem and I did a search and found the solution because at the same time I uploaded the solution sorry and sorry for me bad englis

**Comment by fizzy-joon** [comment]
Yea that problem been around and seems some of solutions same as yours worked for some people but not all, good to hear that worked for you and hope some1 out will reach here and get it useful.
