### ISSUE TITLE
Ecid 0x0 iPhone 11 Pro 13.3 instant reboot

### ISSUE THREAD

**Issue by chefdb** [pwn20wndstuff/Undecimus#1701]
![73CB07A6-5651-4C86-9C27-060F0636C4FD](https://user-images.githubusercontent.com/61116252/74611324-83dcb580-50af-11ea-8e85-708a25f668fb.jpeg)
Installed via altstore  on iOS 13.3 iPhone 11 Pro 

Used airplane mode
Dark mode off 
Waited 30 sec after opening

Instant reboot everytime I click jailbreak
Noticed my ecid is 0x0 
 Attached is a screenshot of when the error occurs 

Corrupted ipc_kmsg  ikm_size 

Update** 

I jail broke my iPhone 11 Pro  by toggling the tfpo on off and on

**Comment by andre104623** [comment]
There is something wrong with the 11 max I don’t know if it’s where everyone is getting them from or the phone it’s self but I’m sure pwn will release a fix

**Comment by andre104623** [comment]
When i mean them I mean the unc0ver app

**Comment by stevenfky** [comment]
Same here, iPhone 11 Pro 512 GB 13.3. Installed with (apple developer account )Cydia Impactor, Altstore etc. The phone reboots every time I hit the Jailbreak button :(  ECID 0x0

**Comment by JustAmply** [comment]
Me too.

iPhone 11 Pro Max 256GB 13.3
ECID 0x0

[diagnostics.plist](https://github.com/pwn20wndstuff/Undecimus/files/4210130/diagnostics.plist.txt)

**Comment by andre104623** [comment]
Caused by AltStore it’s on Reddit restore rootfs and uninstall AltStore install iOS ninja and it will be fine

**Comment by andre104623** [comment]
And rejailbreak with unc0ver you download from iOS ninja

**Comment by nooneyy** [comment]
> And rejailbreak with unc0ver you download from iOS ninja

this is not working.
we are still experiencing these issues after installing iosninjas unc0ver, the altstore bug was a whole different thing..

**Comment by andre104623** [comment]
I’m going by what Reddit is saying and they say it’s causing 0x0

**Comment by andre104623** [comment]
Zjailbreak also has the new unc0ver

**Comment by stevenfky** [comment]
So we need a new offset for iPhone 11 Pro and an update for unc0ver I think

**Comment by themacintoshnerd** [comment]
The iPhone12,3 is broken on unc0ver I think that it can’t find the proper offsets

**Comment by andre104623** [comment]
Well that’s not true I just helped another person get his iPhone 11 max to work

**Comment by andre104623** [comment]
Issue #1700

**Comment by themacintoshnerd** [comment]
> Well that’s not true I just helped another person get his iPhone 11 max to work

iPhone 12,3 is the smaller model not the Max the Pro Max is 12,5

**Comment by themacintoshnerd** [comment]
[000008.log](https://github.com/pwn20wndstuff/Undecimus/files/4210203/000008.log)

**Comment by chefdb** [comment]
So what Im Gathering is that we all have same issue on iPhone 11 Pro ( not max) on 13.3.  All have ecid of 0x0.  Hitting jailbreak crashes.  I don’t get a chance to see any error logs

**Comment by MaxJackson1** [comment]
The last Update (4.0.1) fixed this problem, worked on mine.

**Comment by jooles** [comment]
Not here. Still instant reboots on my 11 pro.
If you read twitter the most part of the folks still experiencing the same.

**Comment by Write** [comment]
> The last Update (4.0.1) fixed this problem, worked on mine.

Well I have unc0ver 4.0.0 from AltStore it says already up to date, where did you got it ?

**Comment by MaxJackson1** [comment]
> > The last Update (4.0.1) fixed this problem, worked on mine.
> 
> Well I have unc0ver 4.0.0 from AltStore it says already up to date, where did you got it ?

download it direct from the homepage. https://unc0ver.dev/

**Comment by MaxJackson1** [comment]
> Not here. Still instant reboots on my 11 pro.
> If you read twitter the most part of the folks still experiencing the same.

Enable only "Load Tweaks", "Load Demons", "Dump APTicket", "Disable Updates", "Set boot nonce", "Reload Daemons", "Set get-task-allow" -> All others you need to disable - So it works on my iphone 11 pro (iphone 12,3 D421AP Model)

**Comment by JDLHiguera** [comment]
> 
> 
> > Not here. Still instant reboots on my 11 pro.
> > If you read twitter the most part of the folks still experiencing the same.
> 
> Enable only "Load Tweaks", "Load Demons", "Dump APTicket", "Disable Updates", "Set boot nonce", "Reload Daemons", "Set get-task-allow" -> All others you need to disable - So it works on my iphone 11 pro (iphone 12,3 D421AP Model)

Didn't work for me. Still crashing on Iphone 11 Pro Max (iOS 13.3)

**Comment by MaxJackson1** [comment]
> > > Not here. Still instant reboots on my 11 pro.
> > > If you read twitter the most part of the folks still experiencing the same.
> > 
> > 
> > Enable only "Load Tweaks", "Load Demons", "Dump APTicket", "Disable Updates", "Set boot nonce", "Reload Daemons", "Set get-task-allow" -> All others you need to disable - So it works on my iphone 11 pro (iphone 12,3 D421AP Model)
> 
> Didn't work for me. Still crashing on Iphone 11 Pro Max (iOS 13.3)

With 4.0.1?

**Comment by JDLHiguera** [comment]
> 
> 
> > > > Not here. Still instant reboots on my 11 pro.
> > > > If you read twitter the most part of the folks still experiencing the same.
> > > 
> > > 
> > > Enable only "Load Tweaks", "Load Demons", "Dump APTicket", "Disable Updates", "Set boot nonce", "Reload Daemons", "Set get-task-allow" -> All others you need to disable - So it works on my iphone 11 pro (iphone 12,3 D421AP Model)
> > 
> > 
> > Didn't work for me. Still crashing on Iphone 11 Pro Max (iOS 13.3)
> 
> With 4.0.1?

Yes.  Updated to 4.0.1 using AltStore beta.

**Comment by JDLHiguera** [comment]
Found another guy (https://twitter.com/Life15Psn) with the same error:
https://pbs.twimg.com/media/EQ7RBOXUwAEuNxu?format=jpg&name=4096x4096

**Comment by hitgrrl** [comment]
> > Not here. Still instant reboots on my 11 pro.
> > If you read twitter the most part of the folks still experiencing the same.
> 
> Enable only "Load Tweaks", "Load Demons", "Dump APTicket", "Disable Updates", "Set boot nonce", "Reload Daemons", "Set get-task-allow" -> All others you need to disable - So it works on my iphone 11 pro (iphone 12,3 D421AP Model)

so after trying anything and everything, I finally got my 11 pro (D421AP) to jailbreak using the above steps. Used unc0ver 4.0.1/AltStore 1.2/AltServer latest ver as well. 
I turned on Airplane mode when I first opened unc0ver, waited a couple minutes, then hit JB button. It failed at around step 6 I believe, it rebooted device. Opened unc0ver again, waited two minutes, hit JB again - success! Opened Cydia, updated the listed necessary resources, restarted Springboard,  let phone sit a minute. Opened Cydia again, profit. Have only installed a couple tweaks for now, and will see how it goes. I saved the jailbreak log if anyone is interested.

**Comment by chefdb** [comment]
I have successfully jailbroken my device. 

Airplane more on 

Tfpo toggle on off on , then jailbreak  worked Perfectly :)  only issue I had was notifications of messaging app.  Which I fixed with ldrestart in terminal

**Comment by JeffResc** [comment]
Experiencing this issue still on v4.0.1 on iOS 13.3 (iPhone 11 Pro Max). I’ve tried installing through AltStore, AltServerPatcher, AltDeploy, Xcode and even a few more methods, to 0% success rate. Between each attempt, I was sure to completely remove any sideloaded apps and retried between each. [[View Diagnostic Log](https://pastebin.com/DEJ8JeiN)/[View Screenshot](https://imgur.com/a/WykuWro)].

**Comment by Hauteknits** [comment]
I am also having this issue. I’m on 13.1.2 and the iPhone 11 Pro non-max. I’ve tried disabling find my iPhone, passcode, and airplane mode. As well as the tfp0 toggle. All unsuccessful. I’ve installed w/ AltStore and I’m getting the exact error in the original ss.

**Comment by Hauteknits** [comment]
the issue still exists in v4.0.3

**Comment by arttyyy** [comment]
> the issue still exists in v4.0.3

Yea still have instant crash on 13.3 pro max 😫

**Comment by MaxJackson1** [comment]
Enable only "Load Tweaks", "Load Demons", "Dump APTicket", "Disable Updates", "Set boot nonce", "Reload Daemons", "Set get-task-allow" -> All others you need to disable

**Comment by arttyyy** [comment]
Still crashes, airplane mode and reboot and then let it sit on uncover and jailbreak and crashes. Tried everything. Frustrating lol.

**Comment by jooles** [comment]
See https://twitter.com/pwn20wnd/status/1230595794429890560?s=21

Will be fixed soon.

**Comment by JeffResc** [comment]
But this doesn’t apply to the iPhone Pro Max, which I’m experiencing issues with.

**Comment by jooles** [comment]
To me Pro also implies Pro Max. But let's wait and see.

**Comment by JeffResc** [comment]
I just didn’t think so since the pro and pro Max’s are different devices and could have different offsets. Anyways, this should fix it probably (I hope):

https://twitter.com/razmashat/status/1230959939885109253?s=21

**Comment by jooles** [comment]
This definitely will! Stay strong! :)

**Comment by borkan8** [comment]
👍🏻
