### ISSUE TITLE
Picture message bug

### ISSUE THREAD

**Issue by SavageAUS** [pwn20wndstuff/Undecimus#1865]
**Describe the bug**
When sending or receiving picture messages all I get is an icon not a preview. 

**To Reproduce**
Steps to reproduce the behaviour:
Send or receive a picture message. 

**Screenshots**
![924C6DE1-D373-4FC7-84E9-82F6BD1A2A54](https://user-images.githubusercontent.com/17326832/76506484-27e13300-649b-11ea-8db4-3adaffe72f36.jpeg)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by 2JayCee** [comment]
Only for iMessage or for Text Messages? Or for both?

**Comment by SavageAUS** [comment]
Its both text and iMessage.

**Comment by kevinjohncutler** [comment]
Same here on iPad Pro 13.3.

**Comment by rlopez12** [comment]
I am having the exact issue as originally stated. However:
iPhone 11 Pro Max
iOS version 13.3
unc0ver version 4.3.1
It is still present after multiple rootfs restores
This is occurring with every text and iMessage I receive with a picture.

**Comment by PencilNotPen** [comment]
Same issue. iPhone X 13.3. Most recent unc0ver.

**Comment by Cryptiiiic** [comment]
supposedly fixed in v4.4.0, will close this when it gets released.

**Comment by Cryptiiiic** [comment]
Substitute bug, so update.

**Comment by SavageAUS** [comment]
Update what? Cydia shows no updates for substitute? Do I need to add a repo?

**Comment by SavageAUS** [comment]
@Cryptiiiic Cryptiiiic commented 6 days ago
supposedly fixed in v4.4.0, will close this when it gets released.

So why is it closed now? 4.4.0 is not released and no updates.

**Comment by SavageAUS** [comment]
Closing an issue that isn’t fixed doesn’t make it go away.

**Comment by Cryptiiiic** [comment]
@SavageAUS It is fixed pwn hasn't released the update yet. Github issues are to track unc0ver unfixed bugs.

**Comment by SavageAUS** [comment]
I fail to see how pwn saying it’s fixed means this bug gets closed as I opened the bug and I still have this bug so this issue should not be closed until the update is released and can be confirmed to be fixed. That’s how I run my bug tracker anyway. A bug is a bug until a fix has been pushed / released and this has not been released so therefor still a bug. And if this release is anything like the others it will be a while before it is released. 

These are my thoughts and opinions, not an attack on anyone. Just my 2 cents.

**Comment by Cryptiiiic** [comment]
@SavageAUS I agree but with the particular issue it’s pretty straightforward. No further discussion is needed other than people that are already subscribed. For other issues this might not be the case.
